version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /var/www/html
        volumes:
            - './html:/var/www/html'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_PASSWORD=root
        ports:
            - '3306:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www/html
        volumes:
            - './html:/var/www/html'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_NAME: ${DB_NAME}

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /var/www/html
        volumes:
            - './html:/var/www/html'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_NAME: ${DB_NAME}
