name: Integration Tests

on:
    pull_request:
      branches:
        - master

jobs:
  build-and-run:
    runs-on: ubuntu-22.04
    env:
      DB_HOST: 127.0.0.1
      DB_USER: ${{ secrets.MYSQL_USER }}
      DB_PASS: ${{ secrets.MYSQL_PASSWORD }}
      DB_NAME: ${{ secrets.MYSQL_DATABASE }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Docker Compose
      run:  |
        export DB_HOST=${DB_HOST}
        export DB_USER=${{ secrets.MYSQL_USER }}
        export DB_PASS=${DB_PASS}
        export DB_NAME=${{ secrets.MYSQL_DATABASE }}
        echo ${DB_HOST}
        docker-compose -f docker-compose.yml up -d

    - name: Wait for services to start
      run: sleep 10

    - name: Install Composer dependencies
      run: composer install

    - name: Create and Add Information to File
      run: |
        ls -l
        sudo mkdir -p $GITHUB_WORKSPACE/html
        echo "DB_HOST=127.0.0.1" | sudo tee -a $GITHUB_WORKSPACE/html/.env
        

    - name: Import Database
      run: |
        mysql -h 127.0.0.1 -P 3306 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASE }};"
        mysql -h 127.0.0.1 -P 3306 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} < sql.sql
        curl -u 'admin@alunos.ipca.pt':'ABCDe12345@' http://127.0.0.1:80/api/auth


    - name: Copy files to HTML folder
      run: |
        sudo rsync -av --exclude='html' * html/

    - name: Download Collection From Postman
      run: |
        ls -l
        ls -l html
        pwd
        COLLECTION_UID=30816775-1a3bc6d6-7921-4a45-abd6-31f07e52d0da
        API_KEY=${{ secrets.POSTMAN_API_KEY }}

        curl -X GET \
        "https://api.postman.com/collections/$COLLECTION_UID" \
        -H "Content-Type: application/json" \
        -H "X-Api-Key: $API_KEY" \
        -o collection.json


    - name: Run Postman Collection test
      run: |
          curl -u 'admin@alunos.ipca.pt':'ABCDe12345@' http://127.0.0.1:80/api/auth

    - name: Run Postman Collection
      run: |
        newman run collection.json \
          --env-var "POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY }}" \
          --env-var "API_BASE_URL=http://127.0.0.1:80" 
          


    - name: Stop Docker Compose
      run: |
        sudo docker-compose down
