name: Integration Tests

on:
    pull_request:
      branches:
        - master

jobs:
  build-and-run:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Docker Compose
      run:  docker-compose -f docker-compose.yml up -d

    - name: Wait for services to start
      run: sleep 10

    - name: Install Composer dependencies
      run: composer install

    - name: Copy files to HTML folder
      run: |
        sudo rsync -av --exclude='html' * html/

    - name: Create and Add Information to File
      run: |
        cd html
        ls -l
        sudo echo "DB_HOST=127.0.0.1" > .env
        sudo echo "DB_USER=${{ secrets.MYSQL_USER }}" >> .env
        sudo echo "DB_PASS=${{ secrets.MYSQL_PASSWORD }}" >> .env
        sudo echo "DB_NAME=${{ secrets.MYSQL_DATABASE }}" >> .env
        sudo cat .env
        cd ..

    - name: Import Database
      run: |
        mysql -h 127.0.0.1 -P 3306 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASE }};"
        mysql -h 127.0.0.1 -P 3306 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} < sql.sql
        
        curl -u 'admin@alunos.ipca.pt':'ABCDe12345@' http://127.0.0.1:80/api/auth



    - name: Download Collection From Postman
      run: |
        ls -l
        ls -l html
        pwd
        COLLECTION_UID=30816775-1a3bc6d6-7921-4a45-abd6-31f07e52d0da
        API_KEY=${{ secrets.POSTMAN_API_KEY }}

        curl -X GET \
        "https://api.postman.com/collections/$COLLECTION_UID" \
        -H "Content-Type: application/json" \
        -H "X-Api-Key: $API_KEY" \
        -o collection.json



    - name: Run Postman Collection
      run: |
        curl -u 'admin@alunos.ipca.pt':'ABCDe12345@' http://127.0.0.1:80/api/auth
        newman run collection.json \
          --env-var "POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY }}" \
          --env-var "API_BASE_URL=http://127.0.0.1:80" 
          


    - name: Stop Docker Compose
      run: |
        sudo docker-compose down
