name: PHP Linter

on:
  push:
    branches:
      - master # Change this to your main branch name if it's different
  pull_request:
    branches:
      - master # Change this to your main branch name if it's different

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --no-scripts --no-progress --no-suggest --prefer-dist

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Check PHP coding standards (PSR-12)
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 .

