name: PHP Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PSR-2 checks
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Check PSR-2 compliance
        run: phpcs --standard=PSR2 .
