name: Auto Increment Tag

on:
  push:
    branches:
      - master

jobs:
  auto_increment_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Get latest tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Debug latest tag
        run: |
          cat $GITHUB_ENV

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
            scheme: semver
            increment: patch


      - name: Create new tag
        run: |
          git config --global user.email "auto@ipca.pt"
          git config --global user.name "Automatic"
          new_tag=${{ steps.version.outputs.version }}
          echo $new_tag
          git tag $new_tag
          git push origin $new_tag
