name: Auto Increment Tag

on:
  push:
    branches:
      - master

jobs:
  auto_increment_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Get latest tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Debug latest tag
        run: |
          cat $GITHUB_ENV

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
            scheme: semver
            increment: patch

      - name: Create new tag
        uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}



