name: Auto Increment Tag

on:
  push:
    branches:
      - master

jobs:
  auto_increment_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Get latest tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Debug latest tag
        run: |
          cat $GITHUB_ENV

      - name: Increment tag
        id: increment_tag
        run: |
          current_tag=${{ steps.latest_tag.outputs.latest_tag }}
          echo "current_tag=$current_tag" >> $GITHUB_ENV  # Debugging line
          IFS='.' read -r major minor patch <<< $(echo $current_tag | awk -F'v|-' '{print $2}')
          ((patch++))
          new_tag="v$major.$minor.$patch"
          echo "::set-output name=new_tag::$new_tag"

      - name: Create new tag
        run: |
          git config --global user.email "auto@ipca.pt"
          git config --global user.name "Automatic"
          new_tag=${{ steps.increment_tag.outputs.new_tag }}
          git tag $new_tag
          git push origin $new_tag
