name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml up -d
        working-directory: ./

      - name: Wait for services to start
        run: |
          docker images
          sleep 10

      - name: Tag and Push Memcached image
        run: |
          docker tag memcached:alpine a6573/tp-scc:memcached
          docker push a6573/tp-scc:memcached
        working-directory: ./

      - name: Tag and Push Nginx image
        run: |
          docker tag nginx:alpine a6573/tp-scc:nginx
          docker push a6573/tp-scc:nginx
        working-directory: ./

      - name: Tag and Push MySQL image
        run: |
          docker tag mysql:8.0 a6573/tp-scc:mysql
          docker push a6573/tp-scc:mysql
        working-directory: ./

      - name: Tag and Push PHP-FPM image
        run: |
          docker tag alves-php-fpm:latest a6573/tp-scc:php-fpm
          docker push a6573/tp-scc:php-fpm
        working-directory: ./
