name: Build and Push Docker Images

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        run: docker-compose -f ./docker-compose.yml build
        working-directory: ./

      - name: Tag and Push Memcached image
        run: |
          docker tag memcached:alpine a6573/tp-scc:memcached
          docker push a6573/tp-scc:memcached
        working-directory: ./

      - name: Tag and Push Nginx image
        run: |
          docker tag nginx:alpine a6573/tp-scc:nginx
          docker push a6573/tp-scc:nginx
        working-directory: ./

      - name: Tag and Push MySQL image
        run: |
          docker tag mysql:latest a6573/tp-scc:mysql
          docker push a6573/tp-scc:mysql
        working-directory: ./
