name: Docker Compose Workflow

on:
    pull_request:
        branches:
          - master

jobs:
  build-and-run:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for services to start
      run: sleep 15

    - name: Install Composer dependencies
      run: composer install

    - name: Rename .env-example to .env
      run: mv .env-example .env

    - name: check docker
      run: docker ps

    - name: Check MySQL Container Logs
      run: mysql -h 127.0.0.1 -P 3306 -u root -proot cloud < sql.sql


    - name: Run Tests
      run: |
        vendor/phpunit/phpunit/phpunit

    - name: Stop Docker Compose
      run: |
        sudo docker-compose down
