name: Docker Compose Workflow

on:
    pull_request:
        branches:
          - master

jobs:
  build-and-run:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        docker-compose --version
        docker-compose up -d

    - name: Install Composer dependencies
      run: composer install

    - name: Rename .env-example to .env
      run: mv .env-example .env

    - name: check docker
      run: docker ps

    - name: Wait for MySQL to Initialize
      run: sleep 4

    - name: Check MySQL Container Logs
      run: docker logs cloud-ipca_mysql_1



    - name: Import MySQL SQL Dump
      env:
        MYSQL_DATABASE: cloud
      run: |
        docker exec -it cloud-ipca_mysql_1 /bin/bash
        mysql  -u root -proot < sql.sql

    - name: Run Tests
      run: |
        vendor/phpunit/phpunit/phpunit

    - name: Stop Docker Compose
      run: |
        sudo docker-compose down
