name: Docker Compose Workflow

on:
    pull_request:
        branches:
          - master

jobs:
  build-and-run:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo docker-compose --version
        sudo docker-compose up -d

    - name: Install Composer dependencies
      run: composer install

    - name: Run Tests
      run: |
        vendor/phpunit/phpunit/phpunit

    - name: Stop Docker Compose
      run: |
        sudo docker-compose down
